project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: right

    code-fold: show
    code-summary: "Show the code"
    code-overflow: scroll
    highlight-style: github
    code-block-border-left: "#5a5d3c"

    theme:
      light: Journal

    css: style.css

    grid:
      body-width: 900px
      
    smooth-scroll: true
    link-external-newwindow: true

